# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo this is dev env
  qa-build:
    environment: qa
    needs: dev-build
    runs-on: ubuntu-latest
    steps:
      - run: echo this is qa env
  prod-build:
    environment: production
    needs: qa-build
    runs-on: ubuntu-latest
    steps:
      - run: echo this is prod env
